name: Awesome

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1,12 * * *'

jobs:
  awesome:
    name: Awesome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm run test

      - name: Generate Awesome
        run: |
          npm run start

      - name: Configure git
        run: |
          git config --global user.email "jakpat.m@gmail.com"
          git config --global user.name "WhatTheFar"

      - name: Commit and push changes
        env:
          COMMIT_M: "feat: update contents"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .

          if [ -n "$(git diff --cached)" ]; then
            echo "there are changes";

            last_commit=$(git log -1 --pretty=%B)

            if [ "${last_commit}" == "${COMMIT_M}" ]; then
              git commit --amend -m "${COMMIT_M}"
            else
              git commit -m "${COMMIT_M}"
            fi

            git push
          else
            echo "no changes";
          fi
